version: '3.8'

services:
  portfolio-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:8080"   # 左邊為主機對外 Port(可改 80/443)，右邊為容器內 Nginx 聽的 $PORT
    restart: always
    environment:
      - NODE_ENV=production
